### PR TITLE
Provide better error logging when failing to hydrate the store

### PR DESCRIPTION
**Pull request by okonon**
@fiznool  @dfmartin please merge if you have time. The default hardcoded error message is not specific enough. I ran into issues when i had a syntax error but got hardcoded error instead real one in console output.

### CODE REVIEW

**Comment by joewoodhouse** [comment]
Would it not be better to append `e` onto the log as well, just in case it is useful?

**Comment by okonon** [comment]
I think, as a developer, you can take provide custom error handling I onError function:
```
export function onSyncError(err) {
  console.log(err);
}

export const reducers: ActionReducerMap<appState> = {
  books: booksReducer,
  collection: collectionReducer
};

export const storageSyncReducer = storageSync({
  keys: ['collection'],   // Only sync the `collection` state
  ignoreActions: [        // Don't sync when these actions occur
    BookActions.SELECT,
    CollectionActions.FILTER,
  ],
  hydratedStateKey: 'hydrated', // Add this key to the state
  onSyncError: onSyncError      // If a sync fails
});

```

**Review by okonon — COMMENTED** [review]
Added more descriptive error if hydration fails

**Comment by okonon** [comment]
@joewoodhouse doen - appended error

**Comment by joewoodhouse** [comment]
Will be fixed in 4.2.0

**Pull request closed without merging**
